# k3d-CkaCluster02.yaml
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: CkaCluster02
image: rancher/k3s:v1.29.0-k3s1-alpine  # 保持 Alpine 镜像
servers: 1
agents: 1
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --disable=traefik,metrics-server
        nodeFilters:
          - server:*
volumes:
  - volume: $HOME/.ssh:/root/.ssh  # 密钥挂载（核心配置）
    nodeFilters:
      - server:*
      - agent:*
ports:
  - port: "2222:22"                # SSH 端口映射
    nodeFilters:
      - server:*
  - port: "6443:6443"              # API 端口

