apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume #pvc 名字
spec:
  storageClassName: openebs-localpv
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 10Mi