apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: CkaCluster01
servers: 1
agents: 1
options:
  k3s:
    extraArgs: 
      - arg: --disable=traefik
        nodeFilters:
          - server:*
          - agent:*
ports:  # 
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer